"""Intent Analyzer - Classifies user messages into domains and detects multi-intent.

The Intent Analyzer runs as a lightweight LLM call before the ReAct loop,
determining:
1. Whether the message contains single or multiple independent intents
2. Which domain(s) are relevant (communication, productivity, lifestyle, travel)
3. For multi-intent: sub-task decomposition with dependency ordering
4. Whether the message is ambiguous enough to require clarification

Production hardening layers:

- :class:`FastPathClassifier` — regex short-circuit for greetings / acks /
  cancellations.  Avoids a full LLM round-trip on trivially-classified
  messages (~30% of traffic in most assistants).
- ``confidence`` + ``needs_clarification`` fields on :class:`IntentAnalysis` —
  the analyzer can signal "I'm not sure" instead of forcing a wrong bucket.
- Structured ``slots`` on :class:`SubTask` — typed entities (targets,
  quantities, times, locations) so downstream agents don't re-parse
  natural language.
"""

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class SubTask:
    """A single sub-task extracted from a multi-intent message."""

    id: int
    description: str
    domain: str
    depends_on: List[int] = field(default_factory=list)
    #: Structured slots (typed entities) extracted by the classifier.
    #: Keys are free-form but conventionally include ``target``,
    #: ``quantity``, ``time``, ``location``, ``recipient``.  Downstream
    #: agents may prefer these to re-parsing ``description``.
    slots: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IntentAnalysis:
    """Result of intent analysis."""

    intent_type: str  # "single" or "multi"
    domains: List[str]  # Domains needed (e.g., ["communication", "productivity"])
    needs_memory: bool = True  # Whether long-term memory recall is needed
    sub_tasks: List[SubTask] = field(default_factory=list)
    raw_message: str = ""  # Original user message
    #: Classifier self-reported confidence in ``[0.0, 1.0]``.  Values below
    #: :data:`CLARIFY_CONFIDENCE_THRESHOLD` should trigger a clarification
    #: prompt rather than proceeding with the best-guess classification.
    confidence: float = 1.0
    #: When True, the orchestrator should ask the user to disambiguate
    #: rather than execute.
    needs_clarification: bool = False
    #: Optional clarification question generated by the classifier.
    clarification_question: Optional[str] = None
    #: Root-level structured slots (mirrors :attr:`SubTask.slots` for
    #: single-intent messages).
    slots: Dict[str, Any] = field(default_factory=dict)
    #: Route used to produce this analysis: ``"fast_path"``, ``"embedding"``,
    #: ``"llm"``, or ``"fallback"``.  Useful for metrics + eval.
    source: str = "llm"


VALID_DOMAINS = {"communication", "productivity", "lifestyle", "travel", "general"}

MAX_SUB_TASKS = 5

#: Confidence below this value triggers a clarification request.
CLARIFY_CONFIDENCE_THRESHOLD = 0.55

INTENT_ANALYZER_SYSTEM_PROMPT = """\
You are an intent classifier for a personal AI assistant.

Given the conversation history and the user's latest message, determine:
1. Whether it contains a single intent or multiple independent intents
2. Which domain(s) are needed
3. Whether long-term memory recall is needed
4. How confident you are in this classification
5. Whether the message is ambiguous enough that you should ask the user
   to clarify before proceeding

Domains:
- communication: email, slack, discord, twitter/X, linkedin messaging
- productivity: calendar, todo/reminders, briefing, notion, google workspace, cloud storage, github, cron/scheduling
- lifestyle: expenses/budget, smart home, package tracking, spotify/music, youtube, image generation, important dates
- travel: trip planning, maps/directions/navigation, nearby places, air quality
- general: greeting, chitchat, creative writing, pure factual/knowledge Q&A that NO agent is needed to answer

Domain selection rules:
- Pick the MOST SPECIFIC domain(s) for the task. Do NOT add "general" as a safety-net alongside a specific domain.
- Only use "general" when no specialised agent is needed (greetings, chitchat, factual questions answerable from general knowledge).
- "general" MUST appear alone — never combine it with communication / productivity / lifestyle / travel.
- A scheduled reminder is productivity, even if the content references weather or other topics — don't add "general" or "lifestyle" unless a second agent must be invoked.

needs_memory rules:
- true: when the user references personal history, preferences, past conversations, or context that may be stored in memory (e.g. "that restaurant I mentioned", "my usual flight", "like last time")
- false: for greetings, direct commands, factual questions, tool-based lookups, or anything that doesn't need past context (e.g. "hi", "search flights to NYC", "what's the weather", "log expense $15 lunch")

Confidence rules:
- 1.0: unambiguous, single clear task matching one domain
- 0.8: clear intent but minor ambiguity (e.g., which calendar? which account?)
- 0.6: somewhat ambiguous — best-guess but user might have meant something else
- 0.4 or less: too ambiguous to act on — set needs_clarification=true and provide clarification_question

Ambiguity signals (→ low confidence / needs_clarification):
- Demonstratives without antecedent: "handle that", "do the thing", "like before"
- Missing critical details (who? when? which account?)
- Conflicting or contradictory instructions
- Purely emotional statements without actionable intent

Slots:
Extract typed entities into the "slots" object when present. Common keys:
- target: the primary object of the action (e.g., person, document, item)
- quantity: numeric amount (e.g., "$15", "3 tickets")
- time: absolute or relative time reference (e.g., "tomorrow 3pm", "in 2 hours")
- location: named place or coordinates
- recipient: person/channel receiving a message
Omit keys you cannot extract; do NOT hallucinate values.

Rules:
- Classify based on the FULL conversation context, not just the latest message.
- For conditional logic ("if X then Y", "check X and based on that do Y"), classify as SINGLE intent — the execution engine handles conditions natively.
- For multiple items targeting the same agent ("lunch $15, uber $12, coffee $5"), classify as SINGLE intent.
- Only classify as MULTI when there are genuinely independent tasks that require DIFFERENT agents.
- When classifying as MULTI, identify dependencies: if task B needs the result of task A, mark B as depending on A.
- Each sub-task's description should be a complete, self-contained instruction.

Return strict JSON only:
{
  "intent_type": "single" | "multi",
  "domains": ["domain1", ...],
  "needs_memory": true | false,
  "confidence": 0.0 to 1.0,
  "needs_clarification": true | false,
  "clarification_question": "string or null",
  "slots": {},
  "sub_tasks": []
}

For single intent, sub_tasks must be an empty array.
For multi intent, sub_tasks must have at least 2 entries:
{
  "intent_type": "multi",
  "domains": ["domain1", "domain2"],
  "confidence": 0.9,
  "needs_clarification": false,
  "sub_tasks": [
    {"id": 1, "description": "...", "domain": "...", "depends_on": [], "slots": {}},
    {"id": 2, "description": "...", "domain": "...", "depends_on": [1], "slots": {}}
  ]
}
"""


# ---------------------------------------------------------------------------
# Fast-path regex classifier
# ---------------------------------------------------------------------------

#: Short utterances that can be classified without an LLM call.  The keys
#: are compiled regex patterns; values are partial :class:`IntentAnalysis`
#: attributes.  Keep this list SHORT and HIGH-PRECISION — false positives
#: here bypass the LLM entirely.
_FAST_PATH_RULES: List[tuple] = [
    # (pattern, domain, needs_memory, is_general_ack)
    (
        re.compile(
            r"^\s*(hi|hello|hey|yo|howdy|嗨|你好|您好|哈喽|おはよう|こんにちは|hola)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(thanks?|thank\s+you|thx|ty|谢谢|多谢|ありがとう|gracias|merci)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(ok|okay|okey|got\s+it|sure|fine|cool|great|awesome|nice|好|好的|知道了|明白|行|了解)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(bye|goodbye|cya|see\s+ya|再见|拜拜|さようなら|adiós)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(yes|yeah|yep|yup|是|对|嗯|好啊|はい|sí)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(no|nope|nah|不|不是|不用|いいえ|no)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
    (
        re.compile(
            r"^\s*(cancel|stop|nevermind|never\s+mind|算了|别了|取消)[!.\s]*$",
            re.IGNORECASE,
        ),
        "general",
        False,
    ),
]

#: Upper length bound — fast-path only considers short utterances.  Longer
#: messages almost always have enough substance for the LLM to add value.
_FAST_PATH_MAX_CHARS = 24


class FastPathClassifier:
    """Regex-based classifier for trivially-short utterances.

    Returns ``None`` when no rule matches; the caller should then fall
    through to the LLM classifier.  Designed for **high precision, low
    recall**: we'd rather miss and pay for an LLM call than misclassify.
    """

    def classify(self, user_message: str) -> Optional[IntentAnalysis]:
        if not user_message:
            return None
        text = user_message.strip()
        if len(text) > _FAST_PATH_MAX_CHARS:
            return None
        for pattern, domain, needs_memory in _FAST_PATH_RULES:
            if pattern.match(text):
                return IntentAnalysis(
                    intent_type="single",
                    domains=[domain],
                    needs_memory=needs_memory,
                    raw_message=user_message,
                    confidence=0.99,
                    needs_clarification=False,
                    source="fast_path",
                )
        return None


class IntentAnalyzer:
    """Lightweight LLM-based intent analyzer.

    Classifies user messages into domains and detects multi-intent requests.
    Falls back gracefully to all-domains on any failure.

    Args:
        llm_client: Chat completion client used for the classifier call.
        fast_path: Optional :class:`FastPathClassifier` tried before the
            LLM.  Pass ``None`` to disable fast-pathing entirely.
        embedding_router: Optional L1 embedding router (see
            :mod:`koa.orchestrator.intent_embedding`) tried after the
            fast-path but before the LLM.
    """

    def __init__(
        self,
        llm_client: Any,
        *,
        fast_path: Optional[FastPathClassifier] = ...,  # type: ignore[assignment]
        embedding_router: Optional[Any] = None,
    ):
        self.llm_client = llm_client
        self.fast_path = FastPathClassifier() if fast_path is ... else fast_path
        self.embedding_router = embedding_router

    async def analyze(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, Any]]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> IntentAnalysis:
        """Analyze user message intent and domain classification.

        Receives the same conversation_history and metadata that the main
        ReAct LLM sees, so short follow-ups ("ok", "yes", "然后呢") are
        classified in the context of the preceding exchange.

        Falls back to single-intent with all domains on failure.
        """
        # Fast-path: trivial greetings / acks skip the LLM entirely, but
        # ONLY when there is no conversation history — with history a bare
        # "ok" may be confirming a pending action and needs LLM reasoning.
        if self.fast_path is not None and not (conversation_history or []):
            fp = self.fast_path.classify(user_message)
            if fp is not None:
                logger.debug("[IntentAnalyzer] fast-path hit: %s", fp.domains)
                return fp

        # Embedding L1 router (optional): if the message closely matches a
        # known-intent centroid, reuse that classification and skip LLM.
        if self.embedding_router is not None:
            try:
                embedded = await self.embedding_router.classify(user_message)
                if embedded is not None:
                    logger.debug("[IntentAnalyzer] embedding hit: %s", embedded.domains)
                    return embedded
            except Exception as exc:
                logger.debug("[IntentAnalyzer] embedding router failed: %s", exc)

        messages: List[Dict[str, Any]] = [
            {"role": "system", "content": INTENT_ANALYZER_SYSTEM_PROMPT},
        ]

        # Full conversation history — same as what the main model receives.
        # Only include user/assistant messages (skip tool results to save tokens).
        if conversation_history:
            for m in conversation_history:
                role = m.get("role")
                content = m.get("content")
                if role in ("user", "assistant") and content:
                    # Truncate long assistant responses to keep classifier fast
                    if role == "assistant" and len(content) > 200:
                        content = content[:200] + "..."
                    messages.append({"role": role, "content": content})

        # Inject runtime context (time, location) so the classifier knows
        # situational details — same info the main model gets.
        if metadata:
            context_parts = []
            tz = metadata.get("timezone")
            if tz:
                context_parts.append(f"User timezone: {tz}")
            location = metadata.get("location")
            if location and isinstance(location, dict):
                lat, lng = location.get("lat"), location.get("lng")
                if lat is not None and lng is not None:
                    context_parts.append(f"User location: {lat}, {lng}")
            if context_parts:
                messages.append(
                    {
                        "role": "system",
                        "content": "[Context]\n" + "\n".join(context_parts),
                    }
                )

        messages.append({"role": "user", "content": user_message})
        try:
            response = await self.llm_client.chat_completion(
                messages=messages,
                config={"temperature": 0.0, "max_tokens": 500},
            )
            result_json = self._extract_json(response.content or "")
            if not result_json:
                logger.warning("[IntentAnalyzer] Failed to parse JSON from response")
                return self._fallback(user_message)
            return self._parse_result(result_json, user_message)
        except Exception as e:
            logger.warning(f"[IntentAnalyzer] LLM call failed: {e}")
            return self._fallback(user_message)

    def _fallback(self, user_message: str) -> IntentAnalysis:
        """Safe fallback: single intent with all domains, low confidence."""
        return IntentAnalysis(
            intent_type="single",
            domains=["all"],
            sub_tasks=[],
            raw_message=user_message,
            confidence=0.3,
            needs_clarification=False,
            source="fallback",
        )

    def _parse_result(self, data: dict, user_message: str) -> IntentAnalysis:
        """Parse and validate LLM response into IntentAnalysis."""
        intent_type = data.get("intent_type", "single")
        domains = data.get("domains", ["all"])
        needs_memory = data.get("needs_memory", True)
        confidence = data.get("confidence", 1.0)
        try:
            confidence = max(0.0, min(1.0, float(confidence)))
        except (TypeError, ValueError):
            confidence = 1.0
        needs_clarification = bool(data.get("needs_clarification", False))
        clarification_question = data.get("clarification_question")
        if clarification_question is not None and not isinstance(clarification_question, str):
            clarification_question = None

        # Auto-trip clarification below threshold even if the LLM didn't set it.
        if confidence < CLARIFY_CONFIDENCE_THRESHOLD and not needs_clarification:
            needs_clarification = True
            if not clarification_question:
                clarification_question = (
                    "Could you share a bit more detail? I want to make sure I do the right thing."
                )

        slots = data.get("slots") or {}
        if not isinstance(slots, dict):
            slots = {}

        # Validate domains
        domains = [d for d in domains if d in VALID_DOMAINS]
        # If model appended "general" as a safety-net alongside specific
        # domains, drop it — "general" means "no agent needed" and must
        # never coexist with a specialised domain.
        if len(domains) > 1 and "general" in domains:
            domains = [d for d in domains if d != "general"]
        if not domains:
            domains = ["general"]

        sub_tasks: List[SubTask] = []
        if intent_type == "multi":
            for st in data.get("sub_tasks", []):
                domain = st.get("domain", "general")
                if domain not in VALID_DOMAINS:
                    domain = "general"
                st_slots = st.get("slots") or {}
                if not isinstance(st_slots, dict):
                    st_slots = {}
                sub_tasks.append(
                    SubTask(
                        id=st.get("id", 0),
                        description=st.get("description", ""),
                        domain=domain,
                        depends_on=st.get("depends_on", []),
                        slots=st_slots,
                    )
                )
            # Cap sub-tasks to MAX_SUB_TASKS
            if len(sub_tasks) > MAX_SUB_TASKS:
                logger.warning(
                    f"[IntentAnalyzer] Too many sub-tasks ({len(sub_tasks)}), "
                    f"truncating to {MAX_SUB_TASKS}"
                )
                sub_tasks = sub_tasks[:MAX_SUB_TASKS]
            # Downgrade to single if fewer than 2 sub-tasks
            if len(sub_tasks) < 2:
                logger.info(
                    "[IntentAnalyzer] Downgrading multi-intent to single: "
                    f"only {len(sub_tasks)} sub-task(s) parsed"
                )
                intent_type = "single"
                sub_tasks = []

        return IntentAnalysis(
            intent_type=intent_type,
            domains=domains,
            needs_memory=needs_memory,
            sub_tasks=sub_tasks,
            raw_message=user_message,
            confidence=confidence,
            needs_clarification=needs_clarification,
            clarification_question=clarification_question,
            slots=slots,
            source="llm",
        )

    @staticmethod
    def _extract_json(text: str) -> Optional[Dict[str, Any]]:
        """Extract first JSON object from model output."""
        raw = (text or "").strip()
        if not raw:
            return None
        try:
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else None
        except json.JSONDecodeError:
            pass
        m = re.search(r"\{.*\}", raw, flags=re.DOTALL)
        if not m:
            return None
        try:
            parsed = json.loads(m.group(0))
            return parsed if isinstance(parsed, dict) else None
        except json.JSONDecodeError:
            return None
